#!/usr/bin/env python3
"""Filter an Energon metadataset to JSONL entries readable on this cluster."""

import argparse
import copy
from pathlib import Path

import yaml


def can_open(path: Path) -> bool:
    try:
        with path.open("rb") as stream:
            stream.read(1)
    except OSError:
        return False
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    source = yaml.safe_load(args.input.read_text())
    subset = copy.deepcopy(source)
    excluded: list[Path] = []

    for split_name, split in source["splits"].items():
        entries = split["blend_epochized"]
        readable_entries = []
        for entry in entries:
            data_path = Path(entry["path"])
            index_path = Path(f"{data_path}.idx")
            if can_open(data_path) and can_open(index_path):
                readable_entries.append(entry)
            else:
                excluded.append(index_path)
        subset["splits"][split_name]["blend_epochized"] = readable_entries
        print(f"{split_name}: kept {len(readable_entries)} of {len(entries)} entries")

    header = (
        "# Generated by build_readable_text_subset.py.\n"
        "# Contains only JSONL entries whose payload and .idx can be opened.\n"
    )
    rendered = yaml.safe_dump(subset, sort_keys=False, width=4096)
    args.output.write_text(header + rendered)

    print(f"wrote: {args.output}")
    for index_path in excluded:
        print(f"excluded: {index_path}")


if __name__ == "__main__":
    main()
